<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Adoption_List.aspx.cs" Inherits="FurryFriendFoundation.WebForm13" EnableViewState="true"%>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
     <style>
        /* Grid table container */
        
        .grid {
            max-width: 900px;
            overflow-x: auto; 
            padding: 5%;
            margin-left: auto;
            margin-right: auto;
            margin-top: 10px;
}
        .grid-table {
            width: 100%;
            background-color: white;
            padding: 5%;
            margin-left: auto;
            margin-right: auto;
            
        }  

        /* GridView styling */
        .gridview-style {
            border-collapse: separate;
            border-spacing: 0;
        }

        .gridview-style th,
        .gridview-style td {
            border-right: 1px solid #ddd; /* Vertical lines */
            vertical-align: middle;
        }

        .gridview-style th:first-child,
        .gridview-style td:first-child {
            border-left: 1px solid #ddd; /* Left border for first column */
        }

        .gridview-style th,
        .gridview-style td {
            padding: 8px;
            text-align: left;
        }

        .gridview-style th {
            background-color: #f2f2f2;
        }

        .gridview-style tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .gridview-style tr:hover {
            background-color: #ddd;
        }
        .msgbox1{
            border:2px solid black;
            display:flex;
            align-items:center;
            justify-content:center;
            width:40%;
            height:100px;
            margin-left:30%;
        }
        .bg{
            background-color:white;
        }
        table{
            background-color:white;
        }
        .btn a{
            color:black;
        }
    </style>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="bg">
   <div class="btn">
            <a href="addmin.aspx"> <i class="fa-solid fa-arrow-left"></i></a>
    </div>
        
         <div class="msgbox1">
        <asp:Label ID="Label1" runat="server" Text="Search User by Name:-"></asp:Label>
    &nbsp;&nbsp;
    <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>    
         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Submit" />    
         </div>
          <center><h1>List Of Adoption</h1></center>
         <hr />
        <div class="grid">
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" CssClass="gridview-style" DataKeyNames="Id" ForeColor="Black" OnRowEditing="GridView1_RowEditing" OnRowDeleting="GridView1_RowDeleting" OnRowUpdating="GridView1_RowUpdating" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" >
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="PetParent" HeaderText="PetParent" SortExpression="PetParent" />
                    <asp:BoundField DataField="PetName" HeaderText="PetName" SortExpression="PetName" />
                    <asp:BoundField DataField="PetType" HeaderText="PetType" SortExpression="PetType" />
                    <asp:BoundField DataField="Phno" HeaderText="Phno" SortExpression="Phno" />
                    <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                    <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
                    <asp:BoundField DataField="OwnPets" HeaderText="OwnPets" SortExpression="OwnPets" />
                    <asp:BoundField DataField="Pet" HeaderText="Pet" SortExpression="Pet" />
                    <asp:BoundField DataField="Home" HeaderText="Home" SortExpression="Home" />
                    <asp:BoundField DataField="Age" HeaderText="Age" SortExpression="Age" />
                    <asp:BoundField DataField="EmgContact" HeaderText="EmgContact" SortExpression="EmgContact" />
                    <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" DataFormatString="{0:d}" />
                    <asp:BoundField DataField="Signnatory" HeaderText="Signnatory" SortExpression="Signnatory" />
                </Columns>
           
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" ProviderName="System.Data.SqlClient" SelectCommand="SELECT * FROM [AdoptionList]"></asp:SqlDataSource>
   </div> 
                       
        <asp:Label ID="msg" runat="server" Text=" "></asp:Label>
 </div>      
</asp:Content>
