<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="animalsincare.aspx.cs" Inherits="FurryFriendFoundation.WebForm9" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style>
         .animalsincare{
             border: 2px solid ;
             width: 40%;
             margin-left: 30%;
             background-color: white;   
             padding:10px;
         }
        .auto-style1 {
            width: 136px;
        }
        .bg{
            background-color: white;
        }
        .grid-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 5%;
            margin-left: 30%;
            margin-right: auto;
            
        }

        .grid-table th,
        .grid-table td {
            border: 1px solid #dddddd; /* Add borders to cells */
            padding: 8px;
            text-align: left;
        }

        .grid-table th {
            background-color: #f2f2f2;
        }

        .grid-table tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .grid-table tr:hover {
            background-color: #dddddd;
        }

        .grid-table img {
            display: block;
            margin-left: auto;
            margin-right: auto;
            max-width: 100%;
            max-height: 100%;
        }
        .container {
            padding: 20px;
        }
         .btn a{
            color:black;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="bg">
         <div class="btn">
            <a href="addmin.aspx"> <i class="fa-solid fa-arrow-left"></i></a>
    </div>
        <div class="container">
            <div class="animalsincare">
                <h1>Animals In Care</h1>
                <hr />
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <asp:Label ID="Label1" runat="server" Text="Name" CssClass="control-label"></asp:Label>
                            <asp:TextBox ID="nametxt" runat="server" CssClass="form-control"></asp:TextBox>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <asp:Label ID="Img" runat="server" Text="Image" CssClass="control-label"></asp:Label>
                            <asp:FileUpload ID="FileUpload1" runat="server" CssClass="form-control" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <asp:Label ID="description" runat="server" Text="Description" CssClass="control-label"></asp:Label>
                            <asp:TextBox ID="descriptiontxt" runat="server" TextMode="MultiLine" CssClass="form-control"></asp:TextBox>
                            
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-md-12">
                        <asp:Button ID="submit" runat="server" Text="Submit" CssClass="btn btn-warning" OnClick="submit_Click" BackColor="#FF9900" />
                        <asp:Label ID="msg" runat="server" Text=" " CssClass="text-info"></asp:Label>
                    </div>
                </div>
            </div>
        </div>
        <div class="grid-table">
     <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="Id" OnRowEditing="GridView1_RowEditing" OnRowDeleting="GridView1_RowDeleting" OnRowUpdating="GridView1_RowUpdating" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" >
    <Columns>
        <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
        <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
        <asp:TemplateField HeaderText="Image">
            <ItemTemplate>
                <asp:Image ID="Image1" runat="server" ImageUrl='<%# GetImageUrl(Eval("Imagepath")) %>' Height="70px" Width="150px" />
            </ItemTemplate>
            <EditItemTemplate>
    <asp:FileUpload ID="FileUploadEdit" runat="server" />
    <asp:HiddenField ID="hdnImagePath" runat="server" Value='<%# Bind("Imagepath") %>' />
</EditItemTemplate>

        </asp:TemplateField>
        <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
    </Columns>
</asp:GridView>

 <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" ProviderName="System.Data.SqlClient" SelectCommand="SELECT * FROM [animalinCare]"></asp:SqlDataSource>
       <br />
            </div>
    </div>

    
</asp:Content>
