<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Donation_list.aspx.cs" Inherits="FurryFriendFoundation.WebForm10" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style>
        /* Grid table container */
        .grid-table {
            width: 100%;
            background-color: white;
            padding: 5%;
            margin-left: auto;
            margin-right: auto;
            
        }

        /* Grid container */
        .grid {
            width: 80%;
            margin: auto;
            margin-top: 10px;
        }

        /* GridView styling */
        .gridview-style {
            border-collapse: separate;
            border-spacing: 0;
        }

        .gridview-style th,
        .gridview-style td {
            border-right: 1px solid #ddd; /* Vertical lines */
            vertical-align: middle;
        }

        .gridview-style th:first-child,
        .gridview-style td:first-child {
            border-left: 1px solid #ddd; /* Left border for first column */
        }

        .gridview-style th,
        .gridview-style td {
            padding: 8px;
            text-align: left;
        }

        .gridview-style th {
            background-color: #f2f2f2;
        }

        .gridview-style tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .gridview-style tr:hover {
            background-color: #ddd;
        }
        .bg{
            background-color:white;
        }
        .btn a{
            color:black;
        }
         .msgbox1{
            border:2px solid black;
            display:flex;
            align-items:center;
            justify-content:center;
            width:40%;
            height:100px;
            margin-left:30%;
        }
    </style>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="bg">
     <div class="btn" >
            <a href="addmin.aspx"> <i class="fa-solid fa-arrow-left"></i></a>
         </div>
           <div class="msgbox1">
        <asp:Label ID="Label1" runat="server" Text="Search User by Email-"></asp:Label>
    &nbsp;&nbsp;
    <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>    
         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Submit" />    
         </div>

    <div class="grid-table">
         <center><h1>List Of Donation</h1></center>
         <hr />
        <div class="grid">
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" CssClass="gridview-style" DataKeyNames="Id" ForeColor="Black" OnRowEditing="GridView1_RowEditing" OnRowDeleting="GridView1_RowDeleting" OnRowUpdating="GridView1_RowUpdating" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True"  OnRowCancelingEdit="GridView1_RowCancelingEdit" >
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="Fname" HeaderText="Fname" SortExpression="Fname" />
                    <asp:BoundField DataField="Lname" HeaderText="Lname" SortExpression="Lname" />
                    <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                    <asp:BoundField DataField="SelectedItem" HeaderText="SelectedItem" SortExpression="SelectedItem" />
                    <asp:BoundField DataField="Product" HeaderText="Product" SortExpression="Product" />
                    <asp:BoundField DataField="Money" HeaderText="Money" SortExpression="Money" />
                    <asp:BoundField DataField="DonationDate" HeaderText="DonationDate" SortExpression="DonationDate" DataFormatString="{0:d}" />
                </Columns>
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="#000000" Font-Bold="True" ForeColor="Black" />
                <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                <RowStyle BackColor="#FFFFFF" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="Black" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#808080" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" ProviderName="System.Data.SqlClient" SelectCommand="SELECT * FROM [DonationDetails]"></asp:SqlDataSource>

            <br />
            <br />
            <br />
            <asp:Label ID="msg" runat="server"></asp:Label>
            <br />
        </div>
    </div>
        </div>
</asp:Content>
